# Generated by Django 3.2.12 on 2023-02-18 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_alter_sunglasses_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sunglasses',
            old_name='user',
            new_name='user_id',
        ),
    ]
