# Generated by Django 3.2.12 on 2023-02-18 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_rename_user_sunglasses_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sunglasses',
            old_name='user_id',
            new_name='user',
        ),
    ]
