# Generated by Django 3.2.12 on 2023-02-18 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_alter_sunglasses_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sunglasses',
            name='user',
        ),
        migrations.AlterField(
            model_name='sunglasses',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
