# Generated by Django 3.2.12 on 2023-02-18 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0011_auto_20230218_2006'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
