# Generated by Django 4.1.7 on 2023-02-19 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0012_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='sunglasses',
            name='image',
            field=models.ImageField(default='images/sunglasses/no-img.jpg', upload_to='images/'),
        ),
    ]
