# Generated by Django 4.1.7 on 2023-02-19 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0013_sunglasses_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sunglasses',
            name='image',
            field=models.ImageField(default='static/my_app/sunglasses.jpg', upload_to='static/'),
        ),
    ]
