# Generated by Django 4.1.7 on 2023-02-19 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0014_alter_sunglasses_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sunglasses',
            name='name',
            field=models.CharField(max_length=15),
        ),
    ]
